#
# setup firewalld
#
- name: enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  tags: firewalld

- name: add http service for firewalld
  firewalld:
    zone: public
    service: http
    immediate: true
    permanent: true
    state: enabled
  tags: firewalld

- name: add https service for firewalld
  firewalld:
    zone: public
    service: https
    immediate: true
    permanent: true
    state: enabled
  tags: firewalld
